### PR TITLE
new file

### PR DESCRIPTION
**Pull request by Anurag-Deo**
add names and city

### CODE REVIEW

**Comment by Hello-World463** [comment]
Ankit Singh

**Comment by Krrish-Raj-16** [comment]
Krrish Raj
Patna

**Comment by dharmrajdhaker** [comment]
hello

**Comment by Hello-World463** [comment]
Ankit Singh
Farrukhabad,UP

**Comment by Amitesh-Raj** [comment]
Amitesh Raj

Saharsa

**Comment by dharmrajdhaker** [comment]
Dharmraj  
 CHITTORGARH

**Comment by sangyandayal5** [comment]
Sangyan Dayal
Patna

**Comment by MAURYAARPIT** [comment]
arpit, varanasi

**Comment by Rahul-Nikhate** [comment]
Rahul Nikhate
Nagpur

**Comment by shivaiitp** [comment]
shiva
kanpur

**Comment by mravarshney** [comment]
ADITYA 
LUCKNOW

**Pull request merged**
